Fix trigger mcontrol.chain match issue #599 #627
riscv/riscv-isa-sim pull request #1083
Opened 2022-09-13 01:36 UTC by YenHaoChen

A false condition of variable chain_ok is missing. The false condition should be mcontrol.chain=1 and not matching; otherwise, the chain_ok=true (including initialization).

2022-09-14 01:49 UTC, scottj97 commented
I don't really understand the logic here but I do observe a useful change in triggers.

I have a chained breakpoint set up like so:
tdata1[0]=0x200000000000090b # chain=1 match=2(ge) u=1 store=1 load=1
tdata2[0]=0x000000008000300a
tdata1[1]=0x200000000000018b # match=3(lt) u=1 store=1 load=1
tdata2[1]=0x0000000080003013

This represents a breakpoint on 0x8000300a <= addr < 0x80003013.

Now execute a `ld` to 0x80003002, which loads bytes up through 0x80003009.

Before this PR, this `ld` would trigger a breakpoint trap. Why? It wasn't touching any of the bytes in the range.

After this PR, no breakpoint trap is taken on this instruction.

Note that for aligned accesses, Spike isn't checking every byte in the range -- only the first. For misaligned, it checks every byte. For example, `ld` to 0x80003008 does not trigger the above breakpoint following this PR. (The debug spec under `mcontrol.select` recommends but does not require checking every byte.)

2022-09-20 06:32 UTC, YenHaoChen commented
*Update commit message.

2022-10-03 00:14 UTC, YenHaoChen commented
@timsifive @scottj97 
Is there anything missing from my side?

2022-10-03 16:53 UTC, timsifive requested changes
The logic looks right. Did you check that https://github.com/riscv-software-src/riscv-tests/tree/master/debug tests still pass?

2022-10-03 16:53 UTC, timsifive commented on riscv/triggers.cc
> +    chain_ok = (result!=MATCH_NONE || !triggers[i]->chain());
```suggestion
    chain_ok = result != MATCH_NONE || !triggers[i]->chain();
```

2022-10-04 10:30 UTC, YenHaoChen commented
> The logic looks right. Did you check that https://github.com/riscv-software-src/riscv-tests/tree/master/debug tests still pass?

I have checked that riscv-tests still passes with ```make all```.

2022-10-04 22:19 UTC, timsifive approved these changes

2022-10-04 22:22 UTC, merged