Fix trigger never fire on executing an instruction on devices
riscv/riscv-isa-sim pull request #1084
Opened 2022-09-13 03:49 UTC by YenHaoChen

The trigger matching logic searches TLB for instruction data. However, the TLB will not be filled with instructions on devices; thus, triggers cannot fire when executing instructions on devices.

The PR moves the trigger matching logic to another (upper) function, i.e., from translate_insn_addr() to refill_icache(). The movement makes the instruction data naturally available without searching the TLB and, thus, resolves the issue.

2022-09-13 18:23 UTC, scottj97 commented
This seems like it could be a significant performance degradation, because every single fetch will have to be checked for triggers now. (Versus before, when only fetches from a page with active triggers would check.)

2022-09-13 18:41 UTC, scottj97 requested changes
This change causes some breakpoint traps to change.

My test is proprietary so I cannot share it (sorry) but the setup is:

tdata1[0]=0x2000000000000814
tdata2[0]=0x000000008000281e
tdata1[1]=0x2000000000000000
tdata2[1]=0x000000008000329c
tdata1[2]=0x200000000000010c
tdata2[2]=0x000000008000275d
tdata1[3]=0x2000000000000000
tdata2[3]=0x0000000080003299

Breakpoint 2 is the relevant one here.

pc=8000275a commits with no trap. (compressed instruction)
pc=8000275c takes a breakpoint trap before this change, but no longer does after this change.
pc=80002760 takes a breakpoint trap both before and after this change.

I think it's debatable whether this change is an improvement or not, but at least it ought to be discussed and explained in the PR or commit messages.

2022-09-13 18:51 UTC, aswaterman commented
I agree it isn't acceptable for perf reasons to check the triggers on every instruction fetch.

It should be possible to mitigate the performance issue by only checking the triggers on TLB misses.

2022-09-14 12:26 UTC, YenHaoChen commented
> This change causes some breakpoint traps to change.
> 
> My test is proprietary so I cannot share it (sorry) but the setup is:
> 
> tdata1[0]=0x2000000000000814 tdata2[0]=0x000000008000281e tdata1[1]=0x2000000000000000 tdata2[1]=0x000000008000329c tdata1[2]=0x200000000000010c tdata2[2]=0x000000008000275d tdata1[3]=0x2000000000000000 tdata2[3]=0x0000000080003299
> 
> Breakpoint 2 is the relevant one here.
> 
> pc=8000275a commits with no trap. (compressed instruction) pc=8000275c takes a breakpoint trap before this change, but no longer does after this change. pc=80002760 takes a breakpoint trap both before and after this change.
> 
> I think it's debatable whether this change is an improvement or not, but at least it ought to be discussed and explained in the PR or commit messages.

The triggers indexed 0, 1, and 3 take no effect. The trigger indexed 2 matches PC greater or equal to 0x8000275d. The PC 0x8000275c is less than 0x8000275d and, thus, should not match regardless of this PR.
``` 
tdata1[0]=0x2000000000000814 # chain, s, execute
tdata2[0]=0x000000008000281e
tdata1[1]=0x2000000000000000 # (never match)
tdata2[1]=0x000000008000329c
tdata1[2]=0x200000000000010c # match=2 (ge), u, executeg
tdata2[2]=0x000000008000275d
tdata1[3]=0x2000000000000000 # (never match)
tdata2[3]=0x0000000080003299
```

2022-09-14 13:50 UTC, scottj97 commented
Any behavior change in Spike needs to be deliberate, understood, and explained. The commit message here makes it sound like the only change is that breakpoints in devices will now work. But as I've shown, there are more changes. These changes are not explained and therefore this PR is unacceptable in its current form.

2022-09-14 14:18 UTC, YenHaoChen commented
I agree PR should clarify all the changes being made. The case seems to demonstrate another bug, which was not expected by this PR and is challenging to analyze with only the above information. Can you share some more information for analysis?

2022-09-14 14:20 UTC, scottj97 commented
> I agree PR should clarify all the changes being made. The case seems to demonstrate another bug, which was not expected by this PR and is challenging to analyze with only the above information. Can you share some more information for analysis?

Is the information above not sufficient to reproduce the issue? What more information can I provide?

2022-09-16 01:00 UTC, YenHaoChen commented
The debug spec recommended comparing multiple accessed addresses. Thus, Accessing pc=0x8000275c will be recommended to compare 0x8000275d as well.

![image](https://user-images.githubusercontent.com/39526191/190533417-8c7efcce-aeec-458f-b3b5-72a7e143a72d.png)

The PR is revised to check triggers on TLB misses in the same function translate_insn_addr(), which mitigates the performance impact and keeps checking the recommended addresses.

2022-09-16 18:51 UTC, scottj97 approved these changes
It looks like this will only check triggers on a TLB miss, because of the `return` on line 473 above.

I confirm this undoes the earlier behavior change that I noticed. I haven't tested the performance impact.

2022-09-16 18:59 UTC, aswaterman approved these changes
No discernible perf impact.

2022-09-16 18:59 UTC, merged

2022-09-16 19:00 UTC, aswaterman commented
Thanks!