Pr commit log print value
riscv/riscv-isa-sim pull request #1126
Opened 2022-10-21 06:16 UTC by YenHaoChen

This PR includes two commits to the memory value printing function, commit_log_print_value(). The first commit corrects the number of digits to size-1 accesses. The second commit enhances the capability of irregular-sized accesses, required by the previous commit (https://github.com/riscv-software-src/riscv-isa-sim/commit/e2e66015af4b5fce4bc958e70398f1fb7af7bcd9).

2022-10-21 18:53 UTC, scottj97 commented on riscv/execute.cc
> +      break;
Instead of adding so many more cases here, why not rewrite this as a loop?

I would do that as an additional commit on top of this one, in order to demonstrate that it's just a refactoring and not a functional change from the old system. (At least, not for the aligned sizes.)

2022-10-24 02:16 UTC, YenHaoChen commented on riscv/execute.cc
> +      break;
New commits merges the switch cases. Additionally, it corrects the abort condition on width={1,2,4}.

2022-10-24 17:44 UTC, scottj97 requested changes
I can't see that 37620e1049473402fea17b74007ddb4e1c346717 has any effect.

The call to WRITE_MEM() is outside of `store_slow_path()` where the store gets split into multiple accesses. So I'm not seeing any case where this `commit_log_print_value()` ever needs to print any of these other sizes.

What am I missing here?

2022-10-25 07:14 UTC, YenHaoChen commented
@scottj97 Yes, you are right. This PR does not affect this since the WRITE_MEM() is outside store_slow_path(). I want to log down the physical address of memory writes. Thus, I move the WRITE_MEM() into the store_slow_path(). Sorry for the misleading.

2022-10-25 07:14 UTC, closed without merging