hypervisor extension does not hardwire misa.H
riscv/riscv-isa-sim pull request #1155
Opened 2022-11-23 01:12 UTC by YenHaoChen

This PR corrects the wrong assumption that misa.H is read-only (hardwired).

Reported by @kwalker27 (https://github.com/riscv-software-src/riscv-isa-sim/pull/1154)

2022-12-03 13:59 UTC, scottj97 requested changes
I wrote some comments here when this PR was new, but forgot to submit my review, so they were never published. Sorry for the delay.

2022-12-03 13:59 UTC, scottj97 commented on riscv/csrs.cc
> +    | (proc->extension_enabled('S') ? MHPMEVENT_SINH : 0)
Because you're not checking for `misa` writes that toggle these bits (as the second commit here does for `H`), there's still an assumption here that these `misa` bits are const. So I would use `extension_enabled_const()` for `U` and `S` here.

2022-12-03 13:59 UTC, scottj97 commented on riscv/csrs.cc
> +    for (reg_t i = 3; i <= 31; ++i) {
There are now two places that assume 32 performance counters. (Here and line 234 of processor.cc.) We should first make that into a `#define`.

2022-12-03 13:59 UTC, scottj97 commented on riscv/csrs.cc
> +      const reg_t new_mevent = state->mevent[i - 3]->read() & ~(MHPMEVENT_VUINH | MHPMEVENT_VSINH);
This masking is unnecessary because the `write()` method will do the same masking now that `misa.H==0`.

2022-12-05 00:26 UTC, YenHaoChen commented on riscv/csrs.cc
> +      const reg_t new_mevent = state->mevent[i - 3]->read() & ~(MHPMEVENT_VUINH | MHPMEVENT_VSINH);
The misa_csr_t::unlogged_write() updates ```misa.H``` at the end of the function before updating ```mevent```. Thus, masking is necessary.

2022-12-05 01:01 UTC, YenHaoChen commented on riscv/csrs.cc
> +    for (reg_t i = 3; i <= 31; ++i) {
Add a macro ```#define N_HPMCOUNTERS 29``` in ```processor.h```.

2022-12-05 01:03 UTC, YenHaoChen commented
@scottj97 no worries. Thanks for the comments.

2022-12-05 13:10 UTC, scottj97 requested changes

2022-12-05 13:10 UTC, scottj97 commented on riscv/csrs.cc
> +    | (proc->extension_enabled('H') ? MHPMEVENT_VUINH | MHPMEVENT_VSINH : 0) : 0;
Can you please split bba915f852d01b78daf14062b24c28ec81120e07 to clearly distinguish the bug fix from the refactoring that enables the bug fix? (i.e. the bug fix commit should simply change `extension_enabled_const` to `extension_enabled`)

2022-12-05 13:35 UTC, scottj97 requested changes
Commits now look good, but the bug fix should be reported in the commit message for d4e753925ed693f119a9c047257491ac62a00ac3 instead of 41186bc95e65ef6438cc51b71f2c3abf6c224936

2022-12-05 13:45 UTC, YenHaoChen commented
I copy the report and keep one in the refactor commit because the purpose of the refactor is for the bug fixing.

2022-12-05 13:49 UTC, scottj97 approved these changes

2022-12-05 13:49 UTC, merged