Slightly improve histogram feature
riscv/riscv-isa-sim pull request #1192
Opened 2022-12-21 09:31 UTC by aswaterman

In creating #1191, I noticed the histogram prints in order of PC, rather than order of frequency.  This isn't terribly useful, so swap that around.  After doing so, we can switch to `unordered_map` without a functional change, for a significant speedup.

2022-12-21 15:36 UTC, scottj97 approved these changes
👍

2022-12-21 17:12 UTC, jerryz123 approved these changes

2022-12-21 17:33 UTC, scottj97 requested changes
Please hold off on merging. I've hit some kind of incremental build issue that might be related to this PR. I'm investigating.

2022-12-21 18:03 UTC, aswaterman commented
I could imagine the churn related to the instruction template changes in #1189 and #1190 might be to blame. Please merge if you determine this one is innocent.

2022-12-21 19:46 UTC, scottj97 commented
Maybe you can make some sense of what I've found.

| Clean build first on:  | Then incremental build on: | Outcome |
| ---------------- | --------------------- | ------- |
| #1189 (3cb3d10f058a9ceec6ec93f2aba4c49e2eaa58c1) | #1190 (edcf2d59b7019798f5c2ab303734883936c0b947) | ok      |
| #1189 (3cb3d10f058a9ceec6ec93f2aba4c49e2eaa58c1) | #1191 (b5f68dc55c2b310d24db35a3c7df1ad86509ab61) | ok      |
| #1189 (3cb3d10f058a9ceec6ec93f2aba4c49e2eaa58c1) | #1192 (d6e5a0ed89f1eb918f7a01e9fc7cdf7e71d6d791) | BROKEN! |
| #1190 (edcf2d59b7019798f5c2ab303734883936c0b947) | #1189 (3cb3d10f058a9ceec6ec93f2aba4c49e2eaa58c1) | ok      |
| #1190 (edcf2d59b7019798f5c2ab303734883936c0b947) | #1191 (b5f68dc55c2b310d24db35a3c7df1ad86509ab61) | ok      |
| #1190 (edcf2d59b7019798f5c2ab303734883936c0b947) | #1192 (d6e5a0ed89f1eb918f7a01e9fc7cdf7e71d6d791) | ok      |
| #1191 (b5f68dc55c2b310d24db35a3c7df1ad86509ab61) | #1189 (3cb3d10f058a9ceec6ec93f2aba4c49e2eaa58c1) | ok      |
| #1191 (b5f68dc55c2b310d24db35a3c7df1ad86509ab61) | #1192 (d6e5a0ed89f1eb918f7a01e9fc7cdf7e71d6d791) | ok      |
| #1192 (d6e5a0ed89f1eb918f7a01e9fc7cdf7e71d6d791) | #1189 (3cb3d10f058a9ceec6ec93f2aba4c49e2eaa58c1) | BROKEN! |
| #1192 (d6e5a0ed89f1eb918f7a01e9fc7cdf7e71d6d791) | #1190 (edcf2d59b7019798f5c2ab303734883936c0b947) | ok      |

"Broken" means that `vsetvli` (and possibly any vector instruction?) core dumps.

I haven't tried going to/from any older points before #1189 was merged.

2022-12-21 20:04 UTC, scottj97 commented
Another interesting data point: starting with a clean build from #1189, then incremental to #1190, then incremental to #1192, everything works fine.

It's only going directly from #1189 to #1192 that breaks.

2022-12-21 21:07 UTC, aswaterman commented
I can't make sense of it from that data.  I'll try to replicate your results so I can play around with the problem.

2022-12-21 22:03 UTC, aswaterman commented
OK, at least I can confirm that I can replicate it.  I'll dig into it after my next meeting.

2022-12-22 00:12 UTC, aswaterman commented
@scottj97 Figured it out.  It's a bit esoteric.  We're using `ar rcs` to build the archives prior to linking, which preserves and adds to the archive if it already existed.  This usually works by coincidence because our object files don't change names frequently, so they'll still overwrite their predecessors within the archive.  But because #1189 made new names for some of the objects, we now might end up with multiple objects in the archive with functions of the same name.

In the event of multiple objects satisfying a dependence at link time, I'm not sure which one gets chosen (alphabetical? order added to archive? arbitrary?) but the point is, the wrong version of the function is getting linked in.  From there, it's obvious how the result might be a segfault.

The fix is to delete the archive before building it.  Unfortunately, we're stuck with this broken intermediate state in our tree, but so be it.

I'll PR that fix before merging any other PRs.

2022-12-22 00:15 UTC, scottj97 commented
> frequently, so they'll still overwrite their predecessors within the archive. But because #1189 made new names for some of the objects, we now might end up with multiple objects in the archive with functions of the same name.

But #1190 changes the file names back to the same as before, yes?

If so, as long as I always include both #1189 and #1190, or neither #1189 nor #1190, then I shouldn't have an issue?

2022-12-22 00:18 UTC, aswaterman commented
@scottj97 Right, that passes the smell test.

2022-12-22 00:29 UTC, scottj97 approved these changes
Incremental build issue solved and fixed in #1193

2022-12-22 00:31 UTC, merged