Prevent processor_t from retiring instructions after a WFI
riscv/riscv-isa-sim pull request #1197
Opened 2022-12-27 19:48 UTC by jerryz123

Previously, after a WFI, the next call to `proc->step(n)` would always retire another instruction. With this PR, no instructions will retire until a pending interrupt is seen, regardless of how many times `proc->step(n)` is called.

The primary motivation for this change is for use-cases where `proc->step(n)` is called with small `n`.

2022-12-27 22:50 UTC, aswaterman requested changes
I don’t think this is right, since you must exit WFI-state if any locally unmasked interrupt is pending, even if the interrupt is globally masked, preventing the interrupt from actually being taken. On systems without AIA, that means the exit condition is (mip & mie) != 0.

The old scheme was correct using a very conservative algorithm: don’t ever truly halt on WFI. I like this for its simplicity and would prefer to keep it unless you have a compelling reason to do the stricter thing.

2022-12-27 23:34 UTC, jerryz123 commented
Ok. If its preferable to keep the `step()` loop simpler, then I have an alternative approach that addresses my use case here:

2022-12-27 23:44 UTC, sifiverobert commented
@aswaterman If I am not mistaken debug spec assures WFI is 'terminated' on halt request and STEP is always working.
As far as simulating WFI, correct simulation should IMO suspend execution of a program until next interrupt (what means forever if there is no interrupts). From other side legal implementation of WFI may be just NOP. So probably it is OK for Spike to treat WFI as NOP (for now ...). Full simulation of WFI may not be so easy as we think.

2022-12-27 23:53 UTC, aswaterman commented
@jerryz123 Let’s see what @scottj97 thinks about a corrected version of this PR vs. #1198 (which is obviously harmless but might be useful to fewer people). I’m coming around to this version, but I’d like another opinion.

@sifiverobert it isn’t even clear what “full simulation” would be, since there’s such a breadth of legal behaviors. If most HW developers are implementing WFI in the strictest way, then perhaps that argues for doing so in Spike, even though the NOP-like approach is fully legal.

2022-12-27 23:59 UTC, sifiverobert commented
Agree about 'full simulation' .... I am not sure how WFI (or simulation of interrupts ...) was handled before, but it seems this PR changed it. It means that some older program may produce different PC-flow what may create problems ...

2022-12-28 00:03 UTC, jerryz123 commented
> On systems without AIA, that means the exit condition is (mip & mie) != 0.

In this implementation, nonzero `mip & mie` would set `in_wfi = false` in `take_interrupt`, so I believe the behavior should still respect the exit condition.

2022-12-28 00:06 UTC, jerryz123 commented
Another advantage of this approach is that it avoids inconsistent behavior between
`step(2)` and `step(1); step(1);`

2022-12-28 00:07 UTC, aswaterman approved these changes
Yes, you’re right; I misread the condition under which you were clearing in_wfi. I now believe this is correct, and I think the implementation is clean enough. Let’s still wait for @scottj97 on this one.

2022-12-28 00:10 UTC, sifiverobert commented
> Another advantage of this approach is that it avoids inconsistent behavior between `step(2)` and `step(1); step(1);`

This is certainly good thing! 'Step(a); Step(b);' should work the same as 'Step(a+b)'.

2022-12-28 00:13 UTC, aswaterman commented on riscv/execute.cc
> +        // No pending interrupt is taken, so remain in wfi
Change comment to “no unmasked pending interrupt, so remain in wfi” or similar?

2022-12-29 19:29 UTC, scottj97 commented
I don't have a strong opinion on this.

I won't be able to test any of these PRs until next week, but no need to wait for me.

2022-12-29 19:42 UTC, aswaterman approved these changes
In that case, let's run with it.

2022-12-29 19:42 UTC, merged

2023-01-02 23:49 UTC, timsifive commented
This change breaks external debug through OpenOCD. Looks like spike hangs the first time it executes the `wfi` at https://github.com/riscv-software-src/riscv-isa-sim/blob/master/debug_rom/debug_rom.S#L42.

2023-01-03 01:52 UTC, jerryz123 commented
Sorry, Tim. Does #1209 fix it?