Install meta pkg-config file for Spike.
riscv/riscv-isa-sim pull request #1346
Opened 2023-05-02 13:43 UTC by Wojciech-Bartczak

Using a Spike a stand-alone library is interesting option to develop own solutions based on Spike without the need to directly intake it as source code.
It also creates interface that prevents unrelated changes to Spike itself.

2023-05-02 13:45 UTC, Wojciech-Bartczak commented
Patch addresses problem in fix #549. However, it doesn't remove option to use Spike as a library.
This definitely simplifies creating tools and projects based on Spike without temptation to change Spike itself.

2023-05-02 13:49 UTC, Wojciech-Bartczak commented
The example usage is available here:
https://github.com/Wojciech-Bartczak/spike-as-lib-example

2023-05-18 15:32 UTC, scottj97 requested changes, later dismissed
I don't understand the Make flow well enough to understand what this does, who it benefits, how to use it, etc. So I can't really form an opinion on whether we should merge this or not.

In any case, PRs like this should not have embedded merges in them. If you want to update this to work on the latest master, please use rebase and force-push.

2023-05-18 22:46 UTC, aswaterman commented
This is OK with me, once this is rebased and the commit history is cleaned up.

2023-05-19 11:20 UTC, Wojciech-Bartczak commented
Hi Andrew, Hi Scott,

Thank you for reviewing the change. Although I'm not very familiar with Github, I will ensure that the patch is fixed to meet the standards.

Regarding the functionality, prior to #549, each subproject (`riscv`, `disasm`, etc.) had its own `*.pc` file (a `pkg-config` configuration file for the library), and all libraries were installed. This allowed Spike to be integrated as a library using `pkg-config`, benefiting tooling and internal programs that utilized Spike.

However, one of the subprojects caused a compilation error, leading to #549. As a result, only `disasm` and `fesrv` remained as installed libraries accessible to users through the `pkg-config` mechanism. Although `riscv.so` was still available, it lacked an attached `*.pc` file. Consequently, users had to manually specify the include list and paths for the compiler to build binaries based on `riscv.so`.

This issue arose because the `install-pcs` target was only evaluated for static libraries (specifically, the `install-libs` target).

The patch I created restores half of the libraries to their original state, giving you the option to choose which libraries are delivered/exposed to users through `*.pc` files.

To achieve this, I added an intermediate make variable that is set to `yes` for libraries intended to be externally visible through `pkg-config`. Subsequently, this variable is used to generate the `*.pc` files during the make install step.

I hope this clarifies the rationale behind the changes.

Kind regards,
Wojciech Bartczak.

2023-05-19 20:31 UTC, aswaterman approved these changes

2023-05-19 20:32 UTC, aswaterman commented
Thanks for writing up the explanation.  I believe Scott is out of pocket, so I'll override his review and merge.

2023-05-19 20:32 UTC, merged