SC Instruction Returns Incorrect Value on Trap.
riscv/riscv-isa-sim pull request #1496
Opened 2023-11-07 11:56 UTC by youzi27

_See issue #1495._
### Description
According to the RISC-V ISA specification for the A extension, the SC (Store Conditional ) instruction requires that the address in rs1 be naturally aligned to the size of the operand. This means that for a 64-bit SC.D instruction, the address must be 8-byte aligned. If the address is not naturally aligned, an address misaligned exception or an access-fault exception should be raised.

However, during testing with the Spike simulator, it has been observed that when the SC.D instruction is executed with a misaligned address in rs1, an exception is raised. Additionally, the RD register does not accurately reflect the success or failure of the SC execution. For instance, if the RD register is initially set to 0, it remains 0 even when the SC instruction encounters a trap, suggesting successful execution, which contradicts the expected behavior.

### Expected Behavior
The SC instruction should not succeed when given a misaligned address and should return a non-zero value in the destination register to indicate failure, in accordance with the specification.

### Actual Behavior
When executing sc, due to traps occurring internally, such as misaligned addresses, a non-zero value will not be written to the rd register, implying that the sc execution has failed. Especially when the rd register is originally 0, it is easy to mislead that the execution has been successful.

### Proposed Solution
When executing SC, the RD register should be set to '!false' before performing MMU operations.

2023-11-07 12:31 UTC, youzi27 commented
According to section 8.2 of the RISC-V Unprivileged ISA Specification: If the SC.W fails, the instruction does not write to memory, and it writes a nonzero value to rd.
This behavior is mandated to indicate the failure of the store conditional operation.

2023-11-07 16:17 UTC, scottj97 requested changes
An instruction that takes an exception never writes to its destination register or memory. In effect, the instruction never executed, so the SC never had a chance to succeed or fail. The fact of the exception is sufficient to show that the SC never completed.

2023-11-07 16:22 UTC, scottj97 commented
Also, for next time, please learn about [writing good commit messages](https://cbea.ms/git-commit/).

2023-11-08 00:48 UTC, youzi27 commented
> Also, for next time, please learn about [writing good commit messages](https://cbea.ms/git-commit/).

I see, thank you very much for your explanation.

2023-11-08 00:48 UTC, closed without merging