Fix Spike --device option to pass on args to downstream plugins
riscv/riscv-isa-sim pull request #1522
Opened 2023-12-04 02:23 UTC by joey0320

Relate to this PR https://github.com/ucb-bar/spike-devices/pull/2.
Basically, as the MMIO devices are suppose to be implemented as plugins, we need a way to pass down arguments to the plugins from the top.
Hence, we change the `--device` option to specify the name of the device along with the arguments.
E.g., `--device="mydevice,arg1=hello"`.

2023-12-04 14:52 UTC, scottj97 requested changes
The rationale for this PR needs to be explained here. Pointing to a PR in another project -- especially one that also has no documented rationale! -- is insufficient.

2023-12-04 14:52 UTC, scottj97 commented on riscv/ns16550.cc
> +ns16550_t* ns16550_parse_from_fdt(const void* fdt, const sim_t* sim, reg_t* base, std::vector<std::string> sargs)
Pass by const ref, instead of passing by value, which will make an unnecessary copy of all the strings.

2023-12-04 14:52 UTC, scottj97 commented on riscv/sim.cc
> +             std::vector<device_factory_t*> plugin_device_factories,
It's unfortunate to have to remove `const` here. Isn't there a way you could pass the args into the factories' constructors? So we can keep `const` here?

2023-12-04 19:06 UTC, scottj97 commented
Can you provide a realistic example of an MMIO device that needs arguments passed in via cmdline?

2023-12-04 19:19 UTC, jerryz123 commented on riscv/abstract_device.h
> +  std::vector<std::string> _sargs;
The `_private_var` is a Pythonism. You should just declare this as private.

2023-12-04 19:21 UTC, jerryz123 commented on riscv/sim.cc
> +             std::vector<device_factory_t*> plugin_device_factories,
I don't think so, for dynamically loaded extension libraries, the factories are constructed by the loading mechanism

2023-12-06 20:06 UTC, joonho3020 commented
> Can you provide a realistic example of an MMIO device that needs arguments passed in via cmdline?

The ucb-bar block device is implemented as an MMIO device.
We would like to pass an argument to the block device such that it can read a file and initialize its contents at startup.
However, with the current spike's top level arguments this is impossible.

2023-12-06 20:52 UTC, scottj97 commented
Please squash the commits together. We don't want to have commits that fix issues from an earlier commit in the same PR.

2023-12-07 19:25 UTC, scottj97 approved these changes

2023-12-07 19:51 UTC, aswaterman approved these changes

2023-12-07 19:53 UTC, aswaterman commented
Because this changes the API, the CI tests that are programmed against that API need to change, too.  The failing one is https://github.com/riscv-software-src/riscv-isa-sim/blob/d94fe56b4fbc000d24f68597eb32e13cb73802ef/ci-tests/testlib.c

2023-12-08 22:40 UTC, jerryz123 approved these changes

2023-12-08 22:40 UTC, merged