Support for non-contiguous hartids
riscv/riscv-isa-sim pull request #156
Opened 2017-11-15 23:37 UTC by p12nGH

2017-11-15 23:41 UTC, palmer-dabbelt approved these changes
LGTM

2017-11-15 23:41 UTC, palmer-dabbelt commented on spike_main/spike.cc
> -  sim_t s(isa, nprocs, halted, start_pc, mems, htif_args);
I wouldn't bother with `std::move` here.  If you just make it a `const vector&` you can elide the copy, but it probably doesn't matter.

2017-11-15 23:48 UTC, aswaterman commented
There's at least one other place in Spike that assumes hart ids are contiguous: sim_t::make_dtb, where it prints cpu@ and _intc.

2017-11-15 23:51 UTC, p12nGH commented
Also some commands that take processor id as a parameter don't work correctly as well

2017-11-15 23:54 UTC, mwachs5 commented
You will probably need to change something in the debug module in here as well, as it assumes (I think) that the mapping is 1:1

2017-11-16 00:02 UTC, mwachs5 commented
https://github.com/riscv/riscv-isa-sim/blob/58b6c187df1a5cc066c97a63483d297fd159f241/riscv/debug_module.cc#L149

Here, the core writes its `mhartid` to certain addresses, and the debug module uses that value to update internal state, and return `flags` read data. to index directly into "flags". This is basically assuming a 1:1 mapping between hartsel and mhartid, which I think you are changing in this PR?

2017-11-16 00:03 UTC, mwachs5 requested changes
This needs some additional changes in the debug_module.cc

2017-11-16 00:16 UTC, mwachs5 approved these changes
I rescind my change request, since it doesn't break anything that doesn't use this flag, and doesn't use the debug module

2017-11-16 00:17 UTC, aswaterman commented
Merging now since this won't break anything that doesn't use the new flag, and under the promise that @p12nGH will fix the devicetree and debug module soon.

2017-11-16 00:17 UTC, merged