hvip isn't an alias (proxy) of mip
riscv/riscv-isa-sim pull request #1590
Opened 2024-02-02 02:53 UTC by YenHaoChen

The H extension defines that bit VSEIP, VSTIP, and VSSIP of hvip are writable. (The other bits of hvip are read-only 0.) Only the VSSIP of hip (mip) is an alias of the same bit of hvip. The VSEIP and VSTIP of hip are the logical-OR of ones of hvip and other sources.

The current aliasing (proxy) implementation does not provide the desired behavior. An ISA-level behavior difference is that any platform-specific external and timer interrupt signals directed to VS-level should not be observable through the hvip. For instance, the hvip should not observe the virtual timer interrupt signal from the Sstc extension (vstimecmp CSR), which isn't true in the current implementation.

This commit fixes the issue by giving the hvip a specialized class, hvip_csr_t, and updating the read value of mip to be the logical-OR of hvip.VSEIP and hvip.VSTIP and other sources. The hvip_csr_t aliases the hvip.VSSIP to the mip.VSSIP.

![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/39526191/9c23e823-417b-4bcb-b68d-b10f6008a01f)
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/39526191/6ed55790-efbc-400d-bf9b-fe67b3d0183d)

2024-02-02 09:00 UTC, YenHaoChen commented
Need help on the CI issue.

2024-02-02 18:38 UTC, scottj97 requested changes
Please change the commit message (and PR title) to indicate what is changing. It's not clear from the message if hvip is supposed to be an alias of mip or not.

The latest commit 5927541c771fc3da7a97d95f3232fbab2fd7507b is core dumping on every test I attempt. (1bdc833f382cf39a0fe74202e71ccd62484bd794 was not doing this.)

2024-02-02 18:38 UTC, scottj97 commented on riscv/csrs.cc
> +  return val | (state->csrmap[CSR_HVIP]->read() & (MIP_VSEIP | MIP_VSTIP));
Save `hvip` as a variable in `state_t` and refer to it by name here, instead of looking it up in the `csrmap` every time.

2024-02-02 18:38 UTC, scottj97 commented on riscv/csrs.cc
> +  state->mip->backdoor_write_with_mask(MIP_VSSIP, val & MIP_VSSIP); // hvip.VSSIP is an alias of mip.VSSIP
This seems problematic, as it's not going to log the change to `mip`.

2024-02-05 02:03 UTC, YenHaoChen commented on riscv/csrs.cc
> +  state->mip->backdoor_write_with_mask(MIP_VSSIP, val & MIP_VSSIP); // hvip.VSSIP is an alias of mip.VSSIP
Use write_with_mask() instead of backdoor_write_with_mask() fucntion.

2024-02-05 02:03 UTC, YenHaoChen commented
Update the title and commit message to clarify that the hvip isn't an alias of mip.

2024-02-05 19:40 UTC, scottj97 requested changes
Let me explain what I'm asking for w.r.t. the commit message and PR title.

The old message of "hvip isn't an alias..." describes a fact. Is this is a true or false fact? Is hvip supposed to be an alias? Is it a problem if it is an alias? Or is it a problem if it's not an alias? Was it an alias in the old code? Does this commit change that, so it's not an alias anymore? Or maybe it wasn't an alias and needs to be, so this commit makes it an alias? None of those important questions are answered by that commit title.

Even the new phrasing of "shouldn't" describes a problem, not a change. Okay, I accept that it shouldn't be an alias. So what? What does this commit have to do with that? Does this change it so it's not an alias anymore? I don't know. This is a good title for an issue report, but not a pull request or commit message.

The commit message should include a verb explaining what is changing. How about:

    Fix hvip.VSEIP and hvip.VSTIP so they don't observe platform-specific interrupts

Followed by all the rest of the explanation from 63bd8d89353a95921bb9e77c91cb20f7befe1368

2024-02-07 21:31 UTC, scottj97 approved these changes

2024-02-07 21:57 UTC, aswaterman approved these changes

2024-02-07 21:57 UTC, merged