sstc: STIP and VSTIP of mip reverts behavior if xenvcfg.STCE=0
riscv/riscv-isa-sim pull request #1591
Opened 2024-02-02 06:17 UTC by YenHaoChen

When menvcfg.STCE=0, mip.STIP reverts to its defined behavior as if unsupporting Sstc extension. When henvcfg.STCE=0, mip.VSTIP reverts to its defined behavior as if unsupporting Sstc extension.

2024-02-02 18:44 UTC, scottj97 requested changes
Please change the title and commit message to describe what is changing. Explain in the PR what was wrong with the old code, an example of how it could misbehave, and how this fixes it.

I guess the old code is only problematic if `--isa=Sstc` is enabled? But it's not clear.

2024-02-04 02:37 UTC, YenHaoChen commented
Add additional paragraphs in the commit message to describe an example of misbehaving and the solution's strategy. 

The title was a shortened, one-sentence summary from the spec, which the commit aims to conform to.
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/39526191/17bcce7d-ee01-45e1-9d06-812f2c29660f)
I need help developing a more concise but respectful sentence to the spec.

2024-02-05 19:46 UTC, scottj97 commented
How about this title:

    Teach Sstc to respect xenvcfg.STCE

Followed by the explanation of the problem. The last paragraph in 15cd07d7b4862cecaea6ae90ba20edc317a9f6c4 is unnecessary because it's simply describing the implementation which is already easy to understand from the diff.

2024-02-08 01:54 UTC, scottj97 approved these changes

2024-02-08 01:57 UTC, aswaterman approved these changes

2024-02-08 01:57 UTC, merged