Support per-device arguments and device factory reuse
riscv/riscv-isa-sim pull request #1655
Opened 2024-04-26 02:58 UTC by liuyu81

Device arguments (or `sargs`) is a new feature introduced in #1522. It allows passing extra `sargs` from CLI `--device=factory[,sargs]` option down to MMIO device plugins.

While the use case is definitely sound, previous implementation does *not* really support instantiating multiple devices from the same factory with different sets of arguments. Another limitation (of previous implementation), is that -- due to the injection of per-device `sargs` globally into `device_factory_t` -- it prohibits device factory resue across multiple `sim_t` instances.

As proposed in #1652, we have created this PR to address the above limitations. The fix is three fold,

- we removed `sargs` from `device_factory_t`, and introduced a new type alias `device_factory_sargs_t` to capture <`device_factory_t *`, `sargs`> pairs, this is used to instantiate `sim_t` instances;
- we changed the signature of `device_factory_t::generate_fdt` / `device_factory_t::parse_from_fdt` to take on an extra `sargs` argument, for instantiating devices with per-device arguments;
- we made `device_factory_t` const and potentially resuable across multiple `sim_t` instances.

2024-04-29 19:07 UTC, jerryz123 requested changes
This overall looks good to me. This repo uses a rebase flow for PRs. Rebase your changes on master, instead of merging master into your feature branch.

2024-04-29 19:07 UTC, jerryz123 commented on riscv/clint.cc
> +std::string clint_generate_dts(const sim_t* sim, const std::vector<std::string>& sargs) {
We should mark the `sargs` argument of clint/ns16550/plic as `UNUSED`.

2024-04-30 02:17 UTC, jerryz123 approved these changes

2024-04-30 02:34 UTC, liuyu81 commented
Thanks for the review. I have marked the `sargs` of clint/ns16550/plic as `UNUSED`, and rebased my changes on master.

2024-04-30 02:39 UTC, aswaterman commented
@jerryz123 I don't have time to review this right now, but feel free to merge if you think it's good to go.

2024-05-01 22:08 UTC, merged