Support RISC-V p-ext-proposal v0.9.1
riscv/riscv-isa-sim pull request #637
Opened 2021-02-02 11:08 UTC by hope51607

See the previous PR #572 

Hello, we’re the team from Programming Langauge Lab, NTHU (National Tsing-Hua University), Taiwan and also from Peakhills group.

This PR implements all instructions in the P-Extension Proposal v0.9.1 ([link](https://github.com/riscv/riscv-p-spec/blob/master/P-ext-proposal.adoc)).

I also create riscv/riscv-opcodes#60 PR to add p-ext opcodes in riscv-opcodes.

2021-02-02 11:12 UTC, aswaterman commented
Thank you (again!) for the contribution. We’ll wait for the RVIA zeitgeist to clarify, but hopefully we can merge these patches soon.

2021-02-03 07:37 UTC, aswaterman commented
Now that I've looked at the patches, I still think we need to wait until the major opcode issue is resolved.  `1111111` is reserved for >32-bit instructions, so shouldn't be used by the P extension.  This will get fixed soon through RVIA, I expect.

2021-02-04 07:13 UTC, hope51607 commented
@aswaterman
I have updated encoding to p-ext v0.9.2 which change major opcode "GE80B 1111111" to "OP-P 1110111".

2021-03-08 03:25 UTC, kito-cheng commented on README.md
> +  - P extension, v0.9.1
@hope51607 Could you update version info here? I think it should be 0.9.2 according your latest subject of this PR.

2021-03-08 03:25 UTC, kito-cheng commented
And seems like you need to rebase due to the conflict.

2021-03-08 06:35 UTC, hope51607 commented
@kito-cheng 

Thanks for the review.
I have updated `readme.md` and rebased master branch.

2021-03-08 06:58 UTC, kito-cheng commented
@aswaterman the major opcode is updated, does here any issue for this PR need to fix?

2021-03-09 00:12 UTC, aswaterman commented
I'd like to wait for RVIA to signal that the opcode allocation is acceptable, then I'm happy to merge.

2021-03-09 01:04 UTC, kito-cheng commented
Oh, I didn't aware it's not accept by RVIA, I thought P spec has updated to using that means already accepted, but obviously I am wrong.

2021-04-22 03:46 UTC, chuanhua commented
@aswaterman Krste and I have discussed this and agreed that the major opcode 1110111 (named OP-P in the P extension specification) is a good location for the P extension to do further development work before ratification. Could you help to merge this pull request? Thanks!

2021-04-22 03:58 UTC, aswaterman commented
Great, thanks for the note, @chuanhua.

@hope51607 is this version of the PR ready to merge?

2021-04-22 07:42 UTC, hope51607 commented
@aswaterman yes, this is the version ready to merge, thanks.

2021-04-22 08:00 UTC, aswaterman commented
Cool.  I'll give it another code review this weekend.  It'll get merged in soon.

2021-05-05 20:52 UTC, aswaterman commented
@chihminchao can I recruit your assistance in [re-]reviewing this patch set?

2021-05-06 07:17 UTC, chihminchao commented
@aswaterman of course,  I will review this weekend.

2021-05-10 02:12 UTC, chihminchao requested changes
There is an lost tab.

2021-05-10 02:15 UTC, chihminchao commented
@hope51607  a lost tab is still in disasm.cc. Please help to correct it.

@aswaterman  All parts looks good to me

2021-05-10 04:58 UTC, hope51607 commented
> @hope51607 a lost tab is still in disasm.cc. Please help to correct it.

Done.

2021-05-11 06:15 UTC, merged