mmu: support asid/vmid
riscv/riscv-isa-sim pull request #928
Opened 2022-02-24 06:36 UTC by chihminchao

The change makes [v]satp.asid and hgatp.vmid writtable and supports
maximum length for rv32 and rv64. Software could write and read the
satp.asid to get the valid length or check if the core supports
asid/vmid or not.  However, there is no official way to describe this hardware
capability (device tree or something else).  Two implementation flags
are also added for future use and enabled by default.

Signed-off-by: Chih-Min Chao <chihmin.chao@sifive.com>

2022-02-24 13:21 UTC, aswaterman commented on riscv/csrs.cc
> +  reg_t asid_mask = proc->supports_impl(IMPL_MMU_ASID) ? proc->get_xlen() == 32 ? SATP32_ASID : SATP64_ASID : 0;
It's a minor stylistic point, but I'd suggest breaking up this statement like the following (or whatever you prefer):

    reg_t asid_mask_if_mmu_enabled = proc->get_xlen() == 32 ? SATP32_ASID : SATP64_ASID;
    reg_t asid_mask = proc->supports_impl(IMPL_MMU_ASID) ? asid_mask_if_mmu_enabled : 0;

2022-02-24 13:21 UTC, aswaterman commented
LGTM, but I'd like review from a non-SiFive person.

2022-02-24 15:37 UTC, scottj97 requested changes

2022-02-24 15:37 UTC, scottj97 commented on riscv/csrs.cc
> +        proc->supports_impl(IMPL_MMU_VMID) ? HGATP64_VMID : 0;
This seems to break the `MAX_PADDR_BITS` masking for `hgatp`. (It's still there in `rv64_ppn_mask` for `satp`.)

2022-04-06 09:07 UTC, chihminchao commented on riscv/csrs.cc
> +        proc->supports_impl(IMPL_MMU_VMID) ? HGATP64_VMID : 0;
@scottj97 
I don't understand where hgatp is related to MAX_PADDR_BITS and rv64_ppn_mask. Could you point out that ?

2022-04-06 16:30 UTC, scottj97 commented on riscv/csrs.cc
> +        proc->supports_impl(IMPL_MMU_VMID) ? HGATP64_VMID : 0;
The PPN field in `hgatp` is WARL, same as `satp`, so the spec allows but does not require this masking. I see no reason to allow a bigger PPN than the system supports though.

In any case this commit says it changes ASID/VMID; it says nothing about changing the PPN field too. If you want to change that, it should be a separate commit with an explanation.

2022-04-07 03:25 UTC, chihminchao commented on riscv/csrs.cc
> +        proc->supports_impl(IMPL_MMU_VMID) ? HGATP64_VMID : 0;
Thanks for your clarification.  I didn't notice the removal of MAX_PADDR_BITS in my change.

2022-04-07 03:28 UTC, scottj97 approved these changes

2022-04-07 06:03 UTC, aswaterman commented
I suspect we might eventually want the option to curtail the ASID length, but we can cross that bridge when we come to it.

2022-04-07 06:03 UTC, merged