Fix for issue #990, implements the PBMTE bit in the henvcfg /menvcfg reisters
riscv/riscv-isa-sim pull request #992
Opened 2022-05-09 22:26 UTC by rbuchner-aril

- Implements the `PBMTE` bit in the `henvcfg` /`menvcfg` registers and checks them during TableWalks
- Makes the value `PBMTE==3`, which is reserved in the spec, cause a fault during a TableWalk
- Makes the reset value of `*envcfg.PBMTE = 1` for backward compatibility

2022-05-10 00:17 UTC, scottj97 requested changes

2022-05-10 00:17 UTC, scottj97 commented on riscv/mmu.cc
> +      } else if (!(proc->get_state()->csrmap[CSR_HENVCFG]->read() & HENVCFG_PBMTE) && (pte & PTE_PBMT)) {
Prefer accessing the CSR object directly, i.e. `proc->get_state()->henvcfg->read()`. The `csrmap` is there for dynamic access such as `csrw` instruction execution where the specific CSR is unknown at Spike compile time.

2022-05-10 00:29 UTC, scottj97 commented
@daniellustig would you agree that PTE.PBMT=3, being a reserved value, should cause a page fault?

2022-05-10 13:15 UTC, daniellustig commented
> @daniellustig would you agree that PTE.PBMT=3, being a reserved value, should cause a page fault?

Yes, that matches the spec wording in the virtual address translation process: "...if any bits or encodings that are reserved for
future standard use are set within $pte$, stop and raise a page-fault exception corresponding to the original access type."

2022-05-10 16:19 UTC, scottj97 approved these changes

2022-05-10 21:42 UTC, scottj97 requested changes
Internal discussions revealed some architectural problems with this implementation. @rbuchner-aril is working on it.

2022-05-11 18:07 UTC, scottj97 approved these changes
As of ccfeaa99732479b029ce95fc9b09968c7f3b1f64 this looks in good shape to me.

2022-05-11 18:21 UTC, aswaterman approved these changes
LGTM.

2022-05-11 18:21 UTC, merged